sudo: required

services:
  -  docker

before_install:
  - gem install bundler --pre
  - docker build -t talk2patel/docker-react -f Dockerfile.dev .
  - docker run -e CI=true talk2patel/docker-react npm run test -- --coverage